# Generated by Django 4.0.4 on 2022-04-17 18:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_alter_productvariantprice_product_variant_one_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productvariantprice',
            name='product_variant_one',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_variant_one', to='product.productvariant'),
        ),
        migrations.AlterField(
            model_name='productvariantprice',
            name='product_variant_three',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_variant_three', to='product.productvariant'),
        ),
        migrations.AlterField(
            model_name='productvariantprice',
            name='product_variant_two',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_variant_two', to='product.productvariant'),
        ),
    ]
